name: Docker Image CI

on:
  push:
    branches:
      - development
      - main

jobs:
  build_and_publish:
    runs-on:
      - self-hosted
      - windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          docker login -u ${{ vars.DOCKERHUB_LOGIN }} --password ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ vars.DOCKERHUB_LOGIN }}/${{ github.event.repository.name }}
          tags: |
            type=ref,event=branch
            type=sha,enable=${{ github.ref == 'refs/heads/main' }}
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./API/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}